apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb-staging
  namespace: argocd
spec:
  project: team1
  source:
    chart: yelb
    repoURL: https://charts.fairwinds.com/incubator
    targetRevision: v0.*.*
    helm:
      releaseName: yelb-staging
      parameters:
        - name: "appserver.image.tag"
          value: "8738f73af5eab68e0b0c53954a651661d02d9b7a"
        - name: "ui.image.tag"
          value: "f977a8183648bf7c0304954675212dbe50eb3f84"
        - name: "postgresql.global.postgresql.auth.postgresPassword"
          value: "changemetoaknownsecret"
        - name: "ingress.hostName"
          value: "yelb.staging.hillghost.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yelb-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
