apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb-staging
  namespace: argocd
spec:
  project: team1
  source:
    chart: yelb
    repoURL: https://charts.fairwinds.com/incubator
    targetRevision: v0.*.*
    helm:
      releaseName: yelb-staging
      parameters:
        - name: "appserver.image.tag"
          value: "724e00d78fcf20737423c8ec577c6ac61754251e"
        - name: "ui.image.tag"
          value: "0eef0161419167d838bdc0af4b7744510816fd9c"
        - name: "postgresql.global.postgresql.auth.postgresPassword"
          value: "changemetoaknownsecret"
        - name: "ingress.hostName"
          value: "yelb.staging.hillghost.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yelb-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
