apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb-staging
  namespace: argocd
spec:
  project: team1
  source:
    chart: yelb
    repoURL: https://charts.fairwinds.com/incubator
    targetRevision: v0.*.*
    helm:
      releaseName: yelb-staging
      parameters:
        - name: "appserver.image.tag"
          value: "e1f2e0bdf8007e9cb125b16ca0cdb5f487cb9a9c"
        - name: "ui.image.tag"
          value: "2697126e5571660a07350b23f1add2d038ddac98"
        - name: "postgresql.global.postgresql.auth.postgresPassword"
          value: "changemetoaknownsecret"
        - name: "ingress.hostName"
          value: "yelb.staging.hillghost.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yelb-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
