apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb-staging
  namespace: argocd
spec:
  project: team1
  source:
    chart: yelb
    repoURL: https://charts.fairwinds.com/incubator
    targetRevision: v0.*.*
    helm:
      releaseName: yelb-staging
      parameters:
        - name: "appserver.image.tag"
          value: "80fc5da1c27f26c6945c1e4e7b7c15be35197c48"
        - name: "ui.image.tag"
          value: "317b800489abcdb0e89a3376fcc43f1c3bd9ce6f"
        - name: "postgresql.global.postgresql.auth.postgresPassword"
          value: "changemetoaknownsecret"
        - name: "ingress.hostName"
          value: "yelb.staging.hillghost.com"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: yelb-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
